  
language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: fjDGTQSNc5HJYA56QDw8H5sPXOiJTrKjhv1MUJ/DjlGlv/bDTfGLIYWhn1GVRtXy4F9fookubxM77w+VZblnPJN+GAMMfCEvqvhGFVazMP5uDNE6S9uiEPI7/lZ9U0mcRnm7Rb9A9fnpgjvB0udXEywi0ub2Y7+FZdE3POiFljuw/J8TaYw+psmEt4o5bwLvqE8IGSQTkNJkWHgrmFPKpwWVbPHO56WUMe+yg7Dx+Pe82E/eIaHTI1LxjIETcpQt9Q8rrBoUx34YRkitF/wizeSsyQsF+eVj+PxkE2fup2IrBSzRPwWdxJwEwdPPr3csOab6hUQemlMkh7NlyYODCsK9MG5vMoJLpSjEhSc3S6FxsiYEk6GIchg69YZCga2vc5M9L+aoqkwA7HuNDqXS0Hua30fixvS1a7db1FfpikzkrAJacOryWV0R87SO8roE16gDgWdY7X5O4uGcwtTF+PBabw7gway9+ZXFYSm7RZs4q3N2+ybRiuAKXvzjVJ/aLbBhaJQBf7YsrDck2ZNGYZJNIRwriBbqxfNWvqOzDV7v+aKW9AscImZmyzZj2kNcWkKIY4fsLpcFjhqJ52X85cHzMRv9rpPCmo7CZavHT2XMqoPYgOm4vuDfW5PIE8dkFamW6bKkSFfG5h2mGrOB2eCHvOr3cqgE0MGgDr+zbW0=
  app: lutevi04-test
